### ISSUE TITLE
Crash in UploadActivity$Upload.onPostExecute

### ISSUE THREAD

**Issue by tajobe** [tucisdev/WavyLeaf_android#10]
There is a crash happening in the onPostExecute method of the Upload AsyncTask inside the UploadActivity related to the progress dialog.

By the time we hide the progress dialog, the view/activity it is tied to may have gone away, so the cleanup(reference) of that causes a crash.

Trace:

```
02-25 14:12:04.708 30450 30450 E AndroidRuntime: FATAL EXCEPTION: main
02-25 14:12:04.708 30450 30450 E AndroidRuntime: java.lang.IllegalArgumentException: View not attached to window manager
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.view.WindowManagerGlobal.findViewLocked(WindowManagerGlobal.java:425)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.view.WindowManagerGlobal.removeView(WindowManagerGlobal.java:327)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.view.WindowManagerImpl.removeView(WindowManagerImpl.java:83)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.app.Dialog.dismissDialog(Dialog.java:330)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.app.Dialog.dismiss(Dialog.java:312)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at com.towson.wavyleaf.UploadActivity$Upload.onPostExecute(UploadActivity.java:183)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at com.towson.wavyleaf.UploadActivity$Upload.onPostExecute(UploadActivity.java:1)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.os.AsyncTask.finish(AsyncTask.java:631)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:644)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.os.Handler.dispatchMessage(Handler.java:99)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.os.Looper.loop(Looper.java:137)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at android.app.ActivityThread.main(ActivityThread.java:5455)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at java.lang.reflect.Method.invokeNative(Native Method)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at java.lang.reflect.Method.invoke(Method.java:525)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-25 14:12:04.708 30450 30450 E AndroidRuntime:    at dalvik.system.NativeStart.main(Native Method)
```

**Comment by tajobe** [comment]
This may be caused by UploadActivity immediately calling finish() after creating the AsyncTask. This means that the activity is gone and may be gone by the time the task finishes.
